### ISSUE TITLE
DirHash does not support Windows long path names (over 260 characters).

### ISSUE THREAD

**Issue by tERyceNzAchE** [idrassi/DirHash#10]
Windows 10, Version 1607 (and later) should not have any issues with long path names (with LongPathsEnabled set to 1).  
DirHash should support path names longer than 260 characters.

Currently it will throw the following error:
Error: Input directory/file path is too long. Maximum length is 260 characters

**Comment by idrassi** [comment]
Thanks for the report.
This limitation comes from the use of PathXXX functions from Shlwapi.h which are useful for dealing with path values (`PathCanonicalize`, `PathFindFileName`, `PathMatchSpec`, `PathFileExists` and `PathIsDirector`).

There seem to be equivalent [functions in Pathcch.h](https://docs.microsoft.com/en-us/windows/win32/api/pathcch/) header that are compatible with long path names but they are supported only from Windows 8 with special flags for long path names available only from Windows 10 Version 1703.
I will experiment with these APIs to learn more about these functions. Certainly, I will implement a compatibility layer to allow DirHash to continue running on Windows 7 where these functions don't exist.

**Comment by idrassi** [comment]
I have implemented Windows long path names support and I have published [version 1.17](https://github.com/idrassi/DirHash/releases/tag/DirHash_1.17.0) that contains it.
Let me know if you encounter any issues.

**Comment by bluelayer** [comment]
sorry to interrupt but in this new version when I hang over DirHash executable, one ISO file with 4.52GiB I get `Error: The given input file doesn't exist`. works just fine in 1.16

PS: the file is windows 10_x64_h2 iso

**Comment by idrassi** [comment]
Indeed, I used a function in the new code (`_stat`) that is not compatible with files larger than 4GiB. 
I will implement a fix and publish a new version.
Thank you for the verification!

**Comment by idrassi** [comment]
I have published version 1.18 with the fix.
Can you please confirm that things are ok now?
Thank you for your help.

**Comment by bluelayer** [comment]
perfect now

(you have a typo in DirHash.rc VALUE "FileDescription", "compute Hash of dorectories and files")

**Comment by idrassi** [comment]
Thank you for the confirmation and for the typo report
