### ISSUE TITLE
Support Relative Path Names

### ISSUE THREAD

**Issue by tERyceNzAchE** [idrassi/DirHash#11]
Full path names are stored in the results file, but the directory may be moved at some point after creation and verification will fail.

DirHash should store paths as relative to DirectoryOrFilePath.

**Comment by sergeevabc** [comment]
Let’s compute hashes of files in the current folder.

```console
$ dirhash.exe *.*
$ dirhash *

Error: The given input file doesn't exist
```

Right, perhaps that would work.

```console
$ dirhash.exe .
colorful bla-bla-bla
Blake3 (32 bytes) = D4E2853ECB998AE53763467688F403303CCBAA56CD41C78FD3488EDF2B7F264D
PRESS ENTER
```

Well, at least 1 hash was computed. But which one of 100? And what about 99 remaining files? Oh, that was a _directory hash_, `-sum` switch is for _files_.

```console
$ dirhash.exe . -sum
Using Blake3 to compute checksum of "." ...                                         
AF1349B9F5F9A1A6A0404DEA36DCC9499BCB25C9ADC112B7CC9A93CAE41F3262  .\courgette.log   
9839DCEF4EE3F4A30E6720F24307C0237F0B231612109D01BED6220AE282D49F  .\courgette64.exe 
```
Hooray, at last!

Anyway, what I have learned here is that `-quiet -nowait -nologo` are obligatory switches to stay sane.

**Comment by idrassi** [comment]
@tERyceNzAchE I have implemented relate path support through the introduction of a new switch -sumRelativePath.
Version 1.19 contains this change.

@sergeevabc initially DirHash was developped to compute the hash of folder (that is a single hash value representing the content of the folder). Afterwards, SUM support was added through -sum switch. So, without -sum switch, DirHash will have its original behavior and it will output the hash value of the folder.

**Comment by sergeevabc** [comment]
> @idrassi
> Afterwards, SUM support was added through -sum switch. 

``` console
$ dir /b
birds.txt
pájaros.txt
vögel.txt
птицы-vögel-pájaros-birds.txt
птицы.txt

$ dirhash . -sum
Using Blake3 to compute checksum of "." ...
fb77f6c071bc58d0fcd5013b093d1e3b944df2bb5fad49b4f479dc2f9ce84ada  birds.txt
99f6dc82f4b7c334193c9dbf2a799257f0f566444c8e9e9496b8808cba0bc3aa  pájaros.txt
39b75d2418dbcd18a7ed92b4307e6a77b9b179f8218becd1dad60c966205c913  vögel.txt
0c084284d2292c2c295fe201900d48b7046c8a33e0eb20e8d6b7160d007012ad  птицы-vögel-pájaros-birds.txt
2d7e0379abe022605799524e6bcf997939bfef08130d6adff537b52058e71d01  птицы.txt

BUT

$ dirhash *.txt -sum
Error: The given input file doesn't exist
```
