### ISSUE TITLE
dirhash should not try to hash the file it's reading or writing

### ISSUE THREAD

**Issue by nutpantz** [idrassi/DirHash#12]
First off thanks for dirhash and updating hashcheck (which I have been using for years) I hope you keep developing both.

Dirhash should not try to read it's hash file (set by -t or -verify) when reading or writing a hash file. 
It just complicates things if the hash file is stored with the files being hashed

**Comment by idrassi** [comment]
Thank you for reporting this issue. I have implemented the suggested change in the commit https://github.com/idrassi/DirHash/commit/bc61ea70d97f5442d02ca09c414b861603f906fd and it will be available in upcoming 1.19 version.

**Comment by idrassi** [comment]
1.19 version was released with this fix.
