### ISSUE TITLE
option "-sum" should be supported in ini file

### ISSUE THREAD

**Issue by nutpantz** [idrassi/DirHash#13]
I tried adding 
Sum=True 
Overwrite=true
To my dirhash.ini file and it had no effect.

That is a feature I would love.
As I use them constantly
(So the output is compatible with your hashcheck)

**Comment by idrassi** [comment]
Thank you for suggesting this feature. It is indeed useful.
I have implemented it in the commit https://github.com/idrassi/DirHash/commit/e1e31ac11d02395ae616cfe4fdcd1a1644bfaecc. I also implemented support for "Threads=True" entry in DirHash.ini.

This change will be available in the upcoming 1.19 version.

Please note that when `Sum=True` is specified in DirHash.ini, it will have an effect only if `-verify` is not specified in the command line.

**Comment by idrassi** [comment]
1.19 was release with this change
