### ISSUE TITLE
errors in hash file lines should be reported

### ISSUE THREAD

**Issue by nutpantz** [idrassi/DirHash#14]
Right now if there is one line corrupt dirhash fails to read any lines and report on any hashes. It just errors out

If lines are corrupt in the hash file the line number should be reported but dirhash should try to verify hashes of any good lines.

**Comment by idrassi** [comment]
Thank you for suggesting this enhancement. I have implemented in the commit https://github.com/idrassi/DirHash/commit/2efbe58d28f8984e90d1bb854d190602f0583863 and it will be available in upcoming 1.19 version.

**Comment by idrassi** [comment]
1.19 was released with this change
