### ISSUE TITLE
Cannot Handle Backslash on Root Drive

### ISSUE THREAD

**Issue by comanche** [idrassi/DirHash#16]
**Problem:**  Cannot handle the blackslash on the root drive as in `G:\`.  However, it handle it normally for a root folder as in `G:\a` or `G:\a\`.

To get around this, the forward slash can be used as in `G:/`.

**Comment by idrassi** [comment]
Can you please explain the problem that you are encountering with backslash in root drive? On my side I can use `D:\` for example and it works without issue.

**Comment by comanche** [comment]
After further investigation, I'm seeing the following:

```bat
dirhash.exe D:\ blake3
dirhash.exe "D:\dir with space" blake3
```

The following stops with **Error: The given input file doesn't exist**:

```bat
dirhash.exe "D:\" blake3
dirhash.exe "D:\dir with space\" blake3
```

There seems to be an issue with the trailing `\"`.  The `\` must be escaping the `"`.

This issue is noticed in `cmd.exe` and not PowerShell.

**Comment by idrassi** [comment]
Thank you for the clarification.
This is a limitation of Windows CMD which uses backslash as escape character. For example, in the case of `dirhash.exe "D:\" blake3`, DirHash as argument the string "`D:" blake3`" which of course doesn't exist as a path.

So this is not a DirHash issue and this CMD particularity must be taken into account when typing command line arguments.

**Comment by comanche** [comment]
Thanks for the clarification.
