### ISSUE TITLE
Give option to exclude symbolic links and directory junctions

### ISSUE THREAD

**Issue by comanche** [idrassi/DirHash#18]
Currently, symlinks and directory junctions are followed and generate a `FindFirstFile failed on ...` error if the targest is missing (often true on a backup copy).  Please provide a command switch option to not follow symlink/junction.

**Comment by idrassi** [comment]
Thank you for this proposal. I have implement it a new switch `-nofollow` that tells DirHash to exclude Symbolic Links, Junction Points or Mount Points from hash computation.

I have published version 1.21 that include this change. Feel free to reopen if you encounter any issues.

**Comment by comanche** [comment]
Thank you!
