### ISSUE TITLE
Config DirHash, such as set quiet hashing as default

### ISSUE THREAD

**Issue by zhouyc98** [idrassi/DirHash#2]
First, thanks for your great script, it really helps!

Here I want to ask, could you let users to config the DirHash?  or change the default behavior?
For example, I want to:
1. Set -quiet as default. (It is not necessary to show so many information each time)
2. Auto exits the program every time; thus we don't need to press ENTER to exit. (Actually, it seems that pressing ENTER is the only thing I can do after DirHashing, so I think the manually pressing ENTER is not really needed)

**Comment by idrassi** [comment]
Thank you for this proposal, it will enhance DirHash usability.

I'm thinking of implementing this based on settings written to an ini file (`DirHash.ini`) that can be put on the same folder a DirHash.exe. 
For example, it can have the following format:
```
[Defaults]
Hash=SHA256
Quiet=True
NoWait=True
ShowProgress=False
MSCrypto=False
```

Any comments?

**Comment by zhouyc98** [comment]
Great!

**Comment by idrassi** [comment]
Version 1.10 was published with support for configuration using DirHash.ini.
Below is a sample DirHash.ini file:

```
[Defaults] 
Hash=SHA1
Quiet=False
NoWait=True
ShowProgress=False
clip=True
hashnames=False
stripnames=False
lowercase=False
MSCrypto=False
```
