### ISSUE TITLE
Changes to filenames and directory names are not detected

### ISSUE THREAD

**Issue by brettfire** [idrassi/DirHash#21]
Imagine I have two folders with the following structure:
- [Dir] xyz
  - [Dir] abc
    - [File] test.txt

- [Dir] efg
  - [Dir] lmn
    - [File] test.txt

Now I go and run the following:
```
> DirHash.exe .\xyz sha1 -quiet -nowait
97CE6BED8F31135D64A74675B6E3F1576863EC6D

> DirHash.exe .\efg sha1 -quiet -nowait
97CE6BED8F31135D64A74675B6E3F1576863EC6D
```

The different directory names produce the same hash. Is there an option to actually detect differences to directory names?

**Comment by idrassi** [comment]
@icanhazpython Yes, there is an option to include name in the hash computation. For this, use the switch  `-hashnames` as documented in the Readme. Without this option, the hash is done on the content only.
