### ISSUE TITLE
Why blank line at start of the file? It is possible to update BLAKE3 sources?

### ISSUE THREAD

**Issue by kydex** [idrassi/DirHash#25]
1) When output to file, there is a blank line at the start of the file. Any reason for this? Seems like a bug.
2) Is project still alive? It is possible to update BLAKE3 sources?

**Comment by idrassi** [comment]
Thank you for the report.
I have fixed the blank line issue with the commit https://github.com/idrassi/DirHash/commit/29f648497ce5522295038aeec8fc5b7e920aeae0 and I have update BLAKE3 and BLAKE2 to their latest source code.
I will check of any pending fixes or enhancements and then I will publish new version of DirHash
