### ISSUE TITLE
Use the last folder in DirectoryOrFilePath in the output file

### ISSUE THREAD

**Issue by a84r7a3rga76fg** [idrassi/DirHash#27]
I'd like to see an option that'll put the last folder in DirectoryOrFilePath in the output file e.g. the DirectoryOrFilePath is `C:\test\archive` and the output file includes "archive" i.e. `hash  archive\etc\etc.zip`.

**Comment by idrassi** [comment]
I have pushed a change to implement this feature by adding a new switch `-includeLastDir`: https://github.com/idrassi/DirHash/commit/d8d2b949ddeca811d3f67f36e29012cd0f5ab643

I will publish an official release soon that includes it.
