### ISSUE TITLE
How do I verify files in a checksum?

### ISSUE THREAD

**Issue by a84r7a3rga76fg** [idrassi/DirHash#32]
The file paths are correct.

Checksum:
```
AF1349B9F5F9A1A6A0404DEA36DCC9499BCB25C9ADC112B7CC9A93CAE41F3262  folder\document1.txt
AF1349B9F5F9A1A6A0404DEA36DCC9499BCB25C9ADC112B7CC9A93CAE41F3262  folder\document1.txt
```

Command:
`dirhash "C:\test\folder" -skipError -verify "C:\test\checksum.blake3"`

Output:
```
Error: file "C:\test\folder\document1.txt" not found in checksum file.
Error: file "C:\test\folder\document2.txt" not found in checksum file.
```

`dirhash "C:\test" -skipError -verify "C:\test\checksum.blake3"` doesn't work either

**Comment by idrassi** [comment]
The switch `-includeLastDir` was added to handle this specific case. So you would type:

`dirhash "C:\test\folder" -skipError -verify "C:\test\checksum.blake3"  -includeLastDir`

Sorry for not seeing your question earlier.
